# Generated by Django 4.0.2 on 2022-07-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_profile', models.ImageField(upload_to='')),
                ('star_rate', models.IntegerField()),
                ('review_count', models.PositiveIntegerField()),
                ('tour_sta_time', models.TimeField()),
                ('tour_end_time', models.TimeField()),
                ('car_tour_yn', models.CharField(max_length=1)),
                ('camp_tour_yn', models.CharField(max_length=1)),
                ('etc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_id', models.CharField(max_length=30, unique=True)),
                ('mb_nm', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('mb_type', models.CharField(max_length=2)),
                ('total_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuideMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(max_length=50)),
                ('tour_sta_time', models.TimeField()),
                ('tour_end_time', models.TimeField()),
                ('tour_day', models.DateField()),
                ('guide_mb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.guide')),
                ('user_mb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.member')),
            ],
        ),
        migrations.CreateModel(
            name='Guide_Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.member')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.member'),
        ),
    ]
